#!/bin/sh
# IprediaOS I2P Block Internet
# mattias.ohlsson@inprose.com

echo "IprediaOS I2P Block Internet"
echo "Rewriting firewall rules"

echo "# Firewall configuration written by iprediaos-i2p-block-internet
# Manual customization of this file is not recommended.
*filter
:INPUT DROP [0:0]
:FORWARD DROP [0:0]
:OUTPUT DROP [0:0]
-A INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT
-A INPUT -i lo -j ACCEPT
-A OUTPUT -o lo -j ACCEPT
-A OUTPUT -p tcp --dport 53 -j ACCEPT
-A OUTPUT -p udp --dport 53 -j ACCEPT
-A OUTPUT -m owner --uid-owner i2p -j ACCEPT
COMMIT" > /etc/sysconfig/iptables

echo "Reloading iptables"
service iptables restart
echo "Done"
