#!/bin/sh
# IprediaOS I2P Block Internet
# mattias.ohlsson@inprose.com

echo "IprediaOS I2P Block Internet"
echo "Rewriting firewall rules"

cp /usr/share/iprediaos-i2p-block-internet/iptables-rules /etc/sysconfig/iptables

echo "Reloading iptables"
/bin/systemctl condrestart iptables.service >/dev/null 2>&1 || :
echo "Done"
